// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pijszvcaiafzqwcrofpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpanN6dmNhaWFmenF3Y3JvZnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDIxMTcsImV4cCI6MjA2NTAxODExN30.18Nw5p8fN4BhfFBP02zJjOv6OO9lKPR7km3RPA_zi0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);